### PR TITLE
Navbar Responsive fix and Twitter Icon Update

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
in the header.html file, I have added some bootstrap code in order. Making the div a flex box.

Also in the footer.html file, I have added a CDN link for font-awesome icons In order to create a new logo for twitter.

This pr is a base pr of the original issues created in the Circuitverse blog repo.

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
@tfsomrat @tffarhad  pls. review, this PR resolves an issue reported in circuitverse blog repo. 
issues linked with this PR https://github.com/CircuitVerse/Blog/issues/184 and https://github.com/CircuitVerse/Blog/issues/186

**Comment by tfsomrat** [comment]
Hey @DhairyaMajmudar, I can understand you need this code to fix your site. but as you know it's a free theme for everyone. and we can't accept this kind of PR to fix your site. what I can suggest you is to create a fork of this repo. and then modify it as much as you need. Thank you.

**Comment by DhairyaMajmudar** [comment]
Yes, but since Circuitverse is using the theme as git sub module it's required to be changed here in the original repo.

**Comment by tfsomrat** [comment]
They can change the submodule to the forked repo instead of the main repo.

**Comment by tfsomrat** [comment]
Hey @DhairyaMajmudar, I appreciate your work. but it's not the right way to do it. also you have added `northendlab` screenshot, instead of `northendlab-light`. anyway, I have updated the responsiveness of the header. take a look

**Pull request closed without merging**
