### PR TITLE
fix: contact us form is  getting submitted with empty feedbacks.

### PR DESCRIPTION
**Pull request by subhamkumarr**
## Description:
Contact us form is getting submitted with empty feedback.

### CODE REVIEW

**Comment by subhamkumarr** [comment]
@somratpro

**Comment by subhamkumarr** [comment]
@amenasse @somratpro @Muhammad Sumon @Mehedi Sharif Titas

**Comment by tfsomrat** [comment]
Hey @subhamkumarr, Thanks for submitting this PR. I want to let you know that, we don't want to use JS form validation here. If you need to validate form using JS, then you can simply fork this repo and make changes on your own copy. 
We can simply add HTML validation here by adding `required` attribute with the input field.

**Comment by subhamkumarr** [comment]
@tfsomrat  Sir, can I add `required` to this repo and raise the PR? Will you merge that?

**Comment by tfsomrat** [comment]
You can do that. I'll merge it

**Comment by subhamkumarr** [comment]
Okay Sir

**Comment by subhamkumarr** [comment]
@tfsomrat Sir, I have one doubt: Is CircuitVerse using this? After this merge, will the changes be automatically reflected there?

**Comment by tfsomrat** [comment]
If they are using this as a git submodule, then the next build of their site should reflect the changes. If they are using it as a Hugo module, then they need to update the module version to reflect the changes. If they forked it, then they need to sync changes to update the site.

**Comment by subhamkumarr** [comment]
@tfsomrat they are using it as a submodule. Thank you

**Comment by tachyons** [comment]
@subhamkumarr it will get updated here https://github.com/CircuitVerse/Blog/pull/213

@tfsomrat Thanks from Circuitverse for merging the PR quickly

**Pull request merged**
